---

- name: Switch to prepare Headwind Remote
  ansible.builtin.import_playbook: pre_apuppet.yaml

- name: Start Headwind Remote
  hosts: localhost
  connection: local
  vars_files:
    - config.build.yaml
    - config.defaults.yaml
    - ../config.yaml
  vars:
    compose_project_src: "{{ playbook_dir }}/.."

  tasks:
    - name: Set SSL availability
      ansible.builtin.set_fact:
        ssl_enabled: "{% if is_certbot_enabled %}true{% else %}false{% endif %}"

    - name: (Re)Starting Headwind Remote
      community.docker.docker_compose_v2:
        project_src: "{{ compose_project_src }}"
        state: present
        recreate: always

    - name: Welcome!
      ansible.builtin.debug:
        msg:
          - "To control your mobile devices remotely, install the Headwind Remote Android agent and use the following server URL and secret:"
          - "{% if ssl_enabled %}https{% else %}http{% endif %}://{{ hostname }}{% if ssl_enabled and (web_https_port | default(443) | int) != 443 %}:{{ web_https_port }}{% elif (not ssl_enabled) and (web_http_port | default(80) | int) != 80 %}:{{ web_http_port }}{% endif %}/web-admin/"
          - "API Secret: {{ janus_api_secret }}"
